### ISSUE TITLE
Bug with enzyme .simulate(click) on <div>

### ISSUE THREAD

**Issue by eguyot** [davidtheclark/react-aria-tabpanel#22] opened 2017-12-05 11:04 UTC
Hi. I'm having trouble making my enzyme test work on that `div` that is inside the `li`. 
It doesn't want to simulate a click on a div apparently.
How could I modify the code to make that div a `a` ? 
Is there some parameters we can pass to modify the markup a little ?

**Comment by davidtheclark** [comment] 2017-12-05 13:48
Hi @eguyot. This isn't a bug with the library, but a limitation of Enzyme's `simulate`. I'm open to PRs allowing different elements — so I think this is kind of a duplicate of #21.

**Closed by davidtheclark** 2017-12-05 13:48 UTC
